SECRET_KEY: ''  # 任意字符串即可

# 数据库信息
db:
  host: ''
  port: 3306
  user: ''
  password: ''
  database: 'test_platform'

# token超时时间，单位为秒
token_time_out: 36000

# 分页信息
page:
  pageNum: 1
  pageSize: 20

# 即时达推送 的 系统错误通道
error_push:
  url: 'http://push.ijingniu.cn/send'
  key: ''
